### ISSUE TITLE
Use devel version of pak for setup-r-dependencies

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubverse-actions#37]
Last week, we started to find systemic errors across hubs where packages would fail to install with the message "malformed DESCRIPTION": https://github.com/r-lib/pkgbuild/issues/208

It turned out that the R-universe had updated their protocol and that surfaced a bug in pak. This was fixed in the development version and the solution is to tell GitHub Actions to use the development version of pak (https://github.com/r-lib/pkgbuild/issues/208#issuecomment-2863012401):

```yaml
uses: r-lib/actions/setup-r-dependencies@v2
with:
  pak-version: "devel"
```
